spring:
  application:
    name: auth-service
  data:
    mongodb:
      auto-index-creation: 'true'
      database: chatroom
      port: '27017'
      host: localhost
  #      host: mongo

server:
  port: '0'

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka