spring:
  application:
    name: properties-service
  data:
    mongodb:
      auto-index-creation: 'true'
      database: estatedb
      port: '27017'
      host: localhost
  #      host: mongo
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 5MB
      max-file-size: 5MB

server:
  port: '0'

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka