spring:
  application:
    name: email-service
server:
  port: '0'
debug: true
email:
  host: smtp.gmail.com
  port: 587
  username: <username>
  password: <password>
  debug: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka