spring:
  application:
    name: api-gateway
  redis:
    connect-timeout: 30s
    host: localhost
    port: 6379
    timeout: 5s
  cloud:
    gateway:
      routes:
        - id: secure-data
          uri: lb://auth-service
          predicates:
            - Path=/api/secure/**
          filters:
            - name: RequestRateLimiter
              args:
                keyResolver: "#{@UriKeyResolver}"
                ratelimiter:
                  replenish-rate: 100
                  burst-capacity: 200
        - id: properties-data
          uri: lb://properties-service
          predicates:
            - Path=/api/properties/**
          filters:
            - name: RequestRateLimiter
              args:
                keyResolver: "#{@UriKeyResolver}"
                ratelimiter:
                  replenish-rate: 300
                  burst-capacity: 400
        - id: open-data
          uri: lb://auth-service
          predicates:
            - Path=/api/public/**
          filters:
            - name: RequestRateLimiter
              args:
                keyResolver: "#{@UriKeyResolver}"
                ratelimiter:
                  replenish-rate: 300
                  burst-capacity: 400
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

